config/routes.rb
Verkdagbok::Application.routes.draw do
  resources :entries, path: "faerslur"
  root to: "entries#index"
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  #Validators for entries
  before_save :calculate_duration
  validates :title, :start_time, :end_time, presence: true
  validate :start_time_before_end_time

  #Calulate duration in min., round up to 15 min.
  def calculate_duration
    minutes = ((end_time - start_time) / 60.0).round
    mod = minutes % 15
    self.duration = mod == 0 ? minutes : (minutes + 15 - mod)
  end

  #Custom vailidator, make sure end_time in not less than start_time
  def start_time_before_end_time
    if end_time < start_time
      errors.add(:end_time, "má ekki vera á undan Byrjar")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController


  #Overview of entries
  def index
    #Get date filters
    @from = params[:from_submit].try(:to_date) || 1.month.ago.to_date
    @to = params[:to_submit].try(:to_date) || Date.today

    #Get entries
    @entries = Entry.where(start_time: @from.beginning_of_day..@to.end_of_day)
  end

  #New entry
  def new
    @entry = Entry.new
  end

  #Create entry
  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to entries_path
    else
      render 'new'
    end
  end

  #Show entry
  def show
    @entry = Entry.find(params[:id])
  end

  #Delete entry
  def destroy
    Entry.find(params[:id]).destroy
    redirect_to entries_path
  end

  #Edit entry
  def edit
    @entry = Entry.find(params[:id])
  end

  #Update entry
  def update
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(entry_params)
      redirect_to entries_path
    else
      render 'edit'
    end
  end

  private
    #Parameters for entry
    def entry_params
      params.require(:entry).permit(:title, :body, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.erb
<!-- Used in for create/edit eintry -->

<!-- Render errors if there are-->
<%= render 'shared/error_message', record: entry %>

<!--Title-->
<%= form_for(entry, html: {class: "form-horizontal"}) do |f| %>
<div class="form-group">
  <%= f.label :title, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: "form-control" %>
  </div>
</div>

<!--Body-->
<div class="form-group">
  <%= f.label :body, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_area :body, class: "form-control", rows: 10 %>
  </div>
</div>

<!--Start Time-->
<div class="form-group">
  <%= f.label :start_time, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.datetime_select :start_time %>
  </div>
</div>

<!--End Time-->
<div class="form-group">
  <%= f.label :end_time, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.datetime_select :end_time %>
  </div>
</div>

<!--Submit/Cancel buttons-->
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-large btn-primary" %>
    <%= link_to  "Hætta við", entries_path, class: "btn btn-default" %>
      </div>
</div>
<% end %>

app/views/entries/edit.html.erb
  <!--Edit form for entry-->
  <div class="col-xs-12">
    <h1 class="col-sm-offset-2"><%= t('general.edit') %></h1>
    <!--Render form: see under _form.html.erb-->
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<!-- Shows list of entries-->

<h1><%= t('entries.overview') %></h1>

<!-- Filters for entries-->
<div class="row">
  <div class="col-sm-6">
    <%= form_tag({}, class: "form-inline", method: :get) do %>
      <div class="form-group">
        <%= label_tag :from, "Frá", class: "control-label" %>
        <%= text_field_tag :from, nil, placeholder: "Frá", data: {value: @from.to_s(:db) } %>
      </div>

      <div class="form-group">
        <%= label_tag :to, "Til", class: "control-label" %>
        <%= text_field_tag :to, nil, placeholder: "Til", data: {value: @to.to_s(:db) } %>
      </div>

      <%= submit_tag t('general.search'), class: "btn btn-success btn-sm" %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= link_to t('general.new'), new_entry_path, class:"btn btn-success pull-right" %>
  </div>
</div>

<hr>

<!-- Table showing the entries -->
<div class="table-responsive">
  <table class="table table-striped" >
    <thead>
      <tr>
        <th>
          <%= t('activerecord.attributes.entry.title') %>
        </th>
        <th>
          <%= t('activerecord.attributes.entry.start_time') %>
        </th>
        <th>
          <%= t('activerecord.attributes.entry.end_time') %>
        </th>
        <th>
          <%= t('activerecord.attributes.entry.duration') %>
        </th>
        <th>
          <%= t('general.edit') %>
        </th>
         <th>
          <%= t('general.destroy') %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @entries.each do |entry| %>
      <tr>
        <td>
          <%= link_to entry.title, entry %>
        </td>
        <td>
          <%= l entry.start_time %>
        </td>
        <td>
          <%= l entry.end_time %>
        </td>
        <td>
          <%= entry.duration %> min.
        </td>
         <td>
          <%= link_to t('general.edit'), edit_entry_path(entry), class: "btn btn-warning btn-xs" %>
        </td>
        <td>
          <%= link_to t('general.destroy'), entry, method: :delete, data: { confirm: "Ertu viss?" }, class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">
          Földi skráninga:  <%= @entries.to_a.count %>
        </td>
        <td class="text-right">
          Samtals:
        </td>
        <td>
          <%= @entries.to_a.sum(&:duration) %> min.
        </td>
        <td colspan="2"></td>
      </tr>

    </tfoot>
  </table>
</div>

app/views/entries/new.html.erb
<!--New form for entry-->
<div class="row">
  <div class="col-xs-12">
    <h1 class="col-sm-offset-2"><%= t('general.new') %></h1>
    <!--Render form: see under _form.html.erb-->
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<!--Display form for entry-->
<div class="row">
  <div class="col-xs-12">
    <h1>
      <%= @entry.title %> <small><%= @entry.duration %> min.</small>
    </h1>

    <p>
      <%= @entry.body %>
    </p>

    <strong>
      <%= l @entry.start_time %> - <%= l @entry.end_time %>
    </strong>

    <br>
    <br>

    <div>
      <%= link_to entries_path, class: "btn btn-default" do  %>
        Til baka
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Verkdagbok">
    <meta name="author" content="Gudmundur D. Jakobsson">

    <title>Verkdagbók</title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!--Navigation-->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Verkdagbók", root_path , class: "navbar-brand" %>
        </div>
      </div>
    </div>

    <!-- Body -->
    <div class="container">

        <%= yield %>

    </div><!-- /.container -->
  </body>
</html>

app/views/shared/_error_message.html.erb
<!--Show erroes if there are-->
<% if record.errors.any? %>
<div id="error_explanation" class="col-sm-10 col-sm-offset-2">
  <div class="alert alert-danger">
    Formið inniheldur eftirfarandi villur:
    <ul>
      <% record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>